In [1]:
import fortran_cython_examples
import numpy as np
# import numba as nb

In [2]:
f = fortran_cython_examples.module_variable
f = fortran_cython_examples.dtype1

In [3]:
var1 = np.empty((3),dtype=np.dtype(('S', 20)),order='F')
var1[0] = "{:20}".format("hello")
var1[1] = "{:20}".format("nias")
var1[0] = "hello"
var1[1] = "nick"


In [5]:
a = f.mytype()

In [11]:
a.arr3 = np.array([1,2],dtype=np.int32)

In [12]:
a.arr3

array([1, 2], dtype=int32)

In [34]:
var1

array([b'hello', b'nick',
       b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p\x82\x04\x81\x14'],
      dtype='|S20')

In [18]:
a = np.array(["hi",'hid      '])

In [11]:
np.dtype(('S', 20))

dtype('S20')

In [1]:
import mytest

In [7]:
mytest.mytest.b = b'gd'

In [45]:
np.array("d",dtype=np.dtype(('S', 8)))

array(b'd', dtype='|S8')

In [8]:
mytest.mytest.b

array(b'11', dtype='|S2')

In [ ]:
cdef pystring2cstring(str pystring):
  # add a null c char, and convert to byes
  cdef bytes cstring = (pystring+'\0').encode('utf-8')
  return cstring

In [69]:
py_list_str = ["hello",'Helasdflkjhlkhlkjhlo']

def pyliststr2cstring(py_list_str, d):
    fmt = "{:"+("%i"%d)+"}"
    n = ""
    for a in py_list_str:
        if len(a) > d:
            n+=a[:d]
        else:
            n+=fmt.format(a)
    return (n+'\0').encode('utf-8')


In [70]:
pyliststr2cstring(py_list_str,10)

b'hello     Helasdflkj\x00'

In [62]:
fmt = '{:10}'
fmt.format("hasdfasdfasdfasdfasdfi")

'hasdfasdfasdfasdfasdfi'

In [95]:
a = np.empty((1),dtype=np.dtype(('U', 10)))

a[0] = "hiasdfaasdfa"


In [96]:
a

array(['hiasdfaasd'], dtype='<U10')

In [15]:
f.arr2 = np.zeros(1,np.int32)

AttributeError: attribute 'arr2' of '_fortran_cython_examples.__module_variable' objects is not writable

In [7]:
v = "hello"
(v+'\0').encode('utf-8')

b'hello\x00'

In [8]:
(v).encode('utf-8')

b'hello'

In [31]:
var = np.zeros((10))

if (10,10) != var.shape:
    raise ValueError("VARIABLE must have shape (10,10), but got (9,10)")

ValueError: VARIABLE must have shape (10,10), but got (9,10)

In [32]:
str(var.shape)

'(10,)'

In [25]:
mytest.a = np.zeros(9)get

ValueError: 0-th dimension must be fixed to 8 but got 9


In [38]:
var.shape


(10,)

In [1]:
mytype = fortran_cython_examples.derived_type.mytype

NameError: name 'fortran_cython_examples' is not defined

In [3]:
my = mytype()

In [4]:
my.arr = np.array([1])

In [5]:
%timeit my.a

57 ns ± 0.423 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [8]:
%timeit my.add2a(10)

69.4 ns ± 0.381 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [9]:
my.arr

array([1.])

In [6]:
my.a = 10

In [14]:
@nb.cfunc(nb.types.void(nb.types.int32,nb.types.int32))
def test(a,b):
    b = a + 1

In [19]:
test

<Numba C callback 'test'>

In [21]:
np.empty(100,dtype='c').data

In [8]:
%timeit b = fortran_cython_examples.simple_subroutine.returns_arr1()

1.62 µs ± 23.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [7]:
b

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12], dtype=int32)

In [15]:
my.arr = np.array([1,2,3])

In [4]:
a = my.add2a(100)

In [6]:
print(a)

None


In [24]:
b = 10


@property
def a(self):
    pass
  
@a.setter
def a(self,aa):
    print(a)
    b = aa
    
@a.getter
def a(self):
    return b

In [22]:
a = 1

In [23]:
a

1